name: Build SympAuthy native image

env:
  JAVA_VERSION: 21
  GRAALVM_DISTRIBUTION: 'mandrel'

on:
  workflow_call:

jobs:
  build:
    name: Build SympAuthy native image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create sympauthy-flow directory into resources
        run: mkdir -p server/src/main/resources/sympauthy-flow

      - name: Install sympauthy-flow into resources
        uses: actions/download-artifact@v4
        with:
          name: sympauthy-flow-dist
          path: server/src/main/resources/sympauthy-flow

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Setup Graalvm for JDK ${{ env.JAVA_VERSION }}
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.GRAALVM_DISTRIBUTION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image
        run: gradle nativeCompile

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sympauthy-binary
          path: build/native/nativeCompile/sympauthy
