name: Test

env:
  JAVA_VERSION: 21

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Run tests on all projects
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'
    - run: gradle test --no-daemon
